### ISSUE TITLE
Confused on Basic CRUD Functionality

### ISSUE THREAD

**Issue by mul118** [ashblue/unity-quest-journal#6]
Apologies in advance, but I am really confused on how to:

1) Perform basic persistable CRUD operations using the QuestJournalManager instance or an extension of it, and
2) Sync the UI with the questjournalmanager.

For reference, this is a minimal reproduceable example, assuming the QuestJournalMenu Prefab is used, and the QuestDatabase and QuestJournalSettings are in my Resources folder:

```
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEditor;
using CleverCrow.Fluid.QuestJournals;
using CleverCrow.Fluid.QuestJournals.Quests;
using CleverCrow.Fluid.Utilities;

public class AddQuest : MonoBehaviour {
	public QuestDefinitionBase quest;

	public void Add()
	{
		var questDef =QuestJournalManager.Instance.Quests.Add(quest);
 }   
}
```

Putting in debugging lines like 

var allQuests = QuestJournalManager.Instance.Quests.GetAll();
		allQuests.ForEach(quest => {
			Debug.Log(quest.Description);
		});

Prints out all of the correct quests, both existing and the new added 'quest'.

QuestJournalManager.Instance.Save();

Executes without errors.

However 1) the GUI does not reflect addition of the 'quest' above, and 2) QuestJournalManager.Instance.Save() does not serialize the updated instance.

Would really appreciate your guidance on this, and would love to use your architecture for my projects.

**Comment by ashblue** [comment]
Sorry for the delay in response on this. Does the example code in this project run okay? What you have there looks fine. 

When calling save are you storing the value somewhere? Save doesn't do anything unless you load the returned save data. Let me know if the link below helps.

https://github.com/ashblue/unity-quest-journal?tab=readme-ov-file#save-and-load

**Comment by ashblue** [comment]
Closing this out for now, but feel free to re-open if you're still having trouble.
